FROM python:3.6

LABEL "com.github.actions.name"="Test"
LABEL "com.github.actions.description"="Test the application"
LABEL "com.github.actions.icon"="code"

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
